{% set name = "netpbmfile" %}
{% set version = "2023.6.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netpbmfile-{{ version }}.tar.gz
  sha256: f4fd8a80fbb898eab9cc46243804a12c85854a4cd2455dc1cae379707784da51

build:
  number: 0
  noarch: python
  entry_points:
    - netpbmfile = netpbmfile.netpbmfile:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.19.2
    - matplotlib-base
    - python >=3.8
    - tifffile

test:
  imports:
    - netpbmfile
  commands:
    - pip list
    - pip check
    - netpbmfile --doctest
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read and write Netpbm files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/netpbmfile/

extra:
  recipe-maintainers:
    - goanpeca
