{% set name = "netpbmfile" %}
{% set version = "2022.10.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/netpbmfile-{{ version }}.tar.gz
  sha256: 9cb2eebd94a507473d9b6d2427d382206c2dae9c8c3119f47da517165c49924d

build:
  number: 0
  noarch: python
  entry_points:
    - netpbmfile = netpbmfile.netpbmfile:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - numpy >=1.19.2
    - matplotlib-base >=3.4.3
    - python >=3.8

test:
  imports:
    - netpbmfile
  commands:
    - pip list
    - pip check
    - netpbmfile --doctest
  requires:
    - pip

about:
  home: https://www.lfd.uci.edu/~gohlke/
  summary: Read and write Netpbm files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/cgohlke/netpbmfile/

extra:
  recipe-maintainers:
    - goanpeca
